"""
ASGI config for the task_manager project.

ASGI (Asynchronous Server Gateway Interface) is the standard interface between
async Python web servers and frameworks. This module configures the ASGI
application for the task_manager Django project.

This file is automatically generated by Django's 'startproject' management
command and serves as the entry point for ASGI-compatible servers such as
Daphne, Uvicorn, or Hypercorn.

Usage:
    To run the application with an ASGI server:
    
        uvicorn task_manager.asgi:application --host 0.0.0.0 --port 8000
    
    Or with Daphne:
    
        daphne -b 0.0.0.0 -p 8000 task_manager.asgi:application

Note:
    For production deployments, it's recommended to use a process manager
    like Supervisor or systemd to manage the ASGI server process.

Attributes:
    application: The ASGI application instance that handles incoming requests.
"""
import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'task_manager.settings')

application = get_asgi_application()
