"""
WSGI config for the task_manager project.

WSGI (Web Server Gateway Interface) is the standard interface between Python
web servers and web applications. This module configures the WSGI application
for the task_manager Django project, serving as the entry point for WSGI-compatible
servers such as Gunicorn, uWSGI, or mod_wsgi.

This file is automatically generated by Django's 'startproject' management
command and should not require modification under normal circumstances.

Usage:
    To run the application with a WSGI server:
    
        gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000

    Or with uWSGI:
    
        uwsgi --http :8000 --module task_manager.wsgi:application

Attributes:
    application: The WSGI application callable that handles incoming requests.
        This is the entry point that WSGI servers invoke for each request.

Note:
    For production deployments, it's recommended to use a process manager
    and configure the WSGI server with appropriate worker processes,
    timeouts, and logging settings.
"""
import os

from django.core.wsgi import get_wsgi_application

# Set the default Django settings module for the 'wsgi' command.
# This environment variable tells Django which settings module to use
# when loading the application.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'task_manager.settings')

# Create the WSGI application object.
# This is the callable that WSGI servers will invoke to handle requests.
application = get_wsgi_application()
