line-length = 80

[lint.per-file-ignores]
# init модули могут содержать локальные импорты и логику
"__init__.py" = ["F401"]
# Полностью игнорируем автогенерируемые миграции Django
"**/migrations/*.py" = ["ALL"]
# Игнорируем длину строк в тестах, так как там часто бывают длинные setup-данные
"**/tests.py" = ["E501"]
"**/test_*.py" = ["E501"]
"**/*_tests.py" = ["E501"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]
