sonar.projectKey=unlaudd_middle-python-project-52
sonar.organization=unlaudd

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests.py,**/test_*.py,**/*_tests.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

# Исключаем из анализа качества (но не из покрытия)
sonar.exclusions=**/migrations/**,**/venv/**,**/.venv/**,**/staticfiles/**,**/locale/**
sonar.coverage.exclusions=**/tests.py,**/test_*.py,**/*_tests.py,**/manage.py,**/settings.py,**/wsgi.py,**/asgi.py