sonar.projectKey=unlaudd_middle-python-project-52
sonar.organization=unlaudd

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests.py,**/test_*.py,**/*_tests.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

# Исключаем из анализа качества и безопасности: миграции, venv, статические файлы, локализацию и CI/CD
sonar.exclusions=**/migrations/**,**/venv/**,**/.venv/**,**/staticfiles/**,**/locale/**,.github/workflows/**

# Исключаем из расчета процента покрытия (это не бизнес-логика)
sonar.coverage.exclusions=**/tests.py,**/test_*.py,**/*_tests.py,**/manage.py,**/settings.py,**/wsgi.py,**/asgi.py